# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'card_id_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 240)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 90, 71, 31))
        self.label.setStyleSheet("font: 18pt \".SF NS Text\";")
        self.label.setObjectName("label")
        self.labelCardid = QtWidgets.QLabel(Dialog)
        self.labelCardid.setGeometry(QtCore.QRect(140, 90, 211, 31))
        self.labelCardid.setStyleSheet("font: 18pt \".SF NS Text\";")
        self.labelCardid.setText("")
        self.labelCardid.setObjectName("labelCardid")
        self.labeTime = QtWidgets.QLabel(Dialog)
        self.labeTime.setGeometry(QtCore.QRect(150, 50, 101, 21))
        self.labeTime.setAlignment(QtCore.Qt.AlignCenter)
        self.labeTime.setObjectName("labeTime")
        self.label_text = QtWidgets.QLabel(Dialog)
        self.label_text.setGeometry(QtCore.QRect(110, 195, 101, 21))
        self.label_text.setObjectName("label_text")
        self.label_icon = QtWidgets.QLabel(Dialog)
        self.label_icon.setGeometry(QtCore.QRect(240, 195, 21, 21))
        self.label_icon.setText("")
        self.label_icon.setScaledContents(True)
        self.label_icon.setObjectName("label_icon")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "card id :"))
        self.labeTime.setText(_translate("Dialog", "Time"))
        self.label_text.setText(_translate("Dialog", "Arudino is open"))
