# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(443, 332)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(40, 20, 61, 51))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("icons/Alarm-clock-icon.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_time = QtWidgets.QLabel(Dialog)
        self.label_time.setGeometry(QtCore.QRect(10, 90, 131, 31))
        self.label_time.setStyleSheet("background-color: rgb(158, 155, 150);\n"
"font: 16pt \"Times New Roman\";\n"
"color: rgb(255, 0, 0);")
        self.label_time.setAlignment(QtCore.Qt.AlignCenter)
        self.label_time.setObjectName("label_time")
        self.graphicsView = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView.setGeometry(QtCore.QRect(220, 20, 201, 201))
        self.graphicsView.setObjectName("graphicsView")
        self.label_condition = QtWidgets.QLabel(Dialog)
        self.label_condition.setGeometry(QtCore.QRect(20, 260, 151, 21))
        self.label_condition.setStyleSheet("font: 12pt \"Times New Roman\";")
        self.label_condition.setObjectName("label_condition")
        self.label_led = QtWidgets.QLabel(Dialog)
        self.label_led.setGeometry(QtCore.QRect(170, 262, 21, 21))
        self.label_led.setText("")
        self.label_led.setScaledContents(True)
        self.label_led.setObjectName("label_led")
        self.btnExit = QtWidgets.QPushButton(Dialog)
        self.btnExit.setGeometry(QtCore.QRect(324, 260, 91, 23))
        self.btnExit.setStyleSheet("border: 3px solid red;\n"
"border-radius: 10px;")
        self.btnExit.setObjectName("btnExit")
        self.label_val = QtWidgets.QLabel(Dialog)
        self.label_val.setGeometry(QtCore.QRect(300, 182, 41, 21))
        self.label_val.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 170, 0);")
        self.label_val.setObjectName("label_val")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_time.setText(_translate("Dialog", "TextLabel"))
        self.label_condition.setText(_translate("Dialog", "Arduino is connected"))
        self.btnExit.setText(_translate("Dialog", "Exit"))
        self.label_val.setText(_translate("Dialog", "1000"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
