# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'example_3.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(400, 204)
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 381, 161))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_start_3 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_start_3.setAutoDefault(True)
        self.pushButton_start_3.setObjectName("pushButton_start_3")
        self.gridLayout.addWidget(self.pushButton_start_3, 0, 0, 1, 1)
        self.pushButton_stop_3 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_stop_3.setObjectName("pushButton_stop_3")
        self.gridLayout.addWidget(self.pushButton_stop_3, 0, 1, 1, 1)
        self.probar_3 = QtWidgets.QProgressBar(self.layoutWidget)
        self.probar_3.setProperty("value", 0)
        self.probar_3.setObjectName("probar_3")
        self.gridLayout.addWidget(self.probar_3, 0, 2, 1, 1)
        self.pushButton_start_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_start_2.setObjectName("pushButton_start_2")
        self.gridLayout.addWidget(self.pushButton_start_2, 1, 0, 1, 1)
        self.pushButton_stop_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_stop_2.setObjectName("pushButton_stop_2")
        self.gridLayout.addWidget(self.pushButton_stop_2, 1, 1, 1, 1)
        self.probar_2 = QtWidgets.QProgressBar(self.layoutWidget)
        self.probar_2.setProperty("value", 0)
        self.probar_2.setObjectName("probar_2")
        self.gridLayout.addWidget(self.probar_2, 1, 2, 1, 1)
        self.pushButton_start_1 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_start_1.setObjectName("pushButton_start_1")
        self.gridLayout.addWidget(self.pushButton_start_1, 2, 0, 1, 1)
        self.pushButton_stop_1 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_stop_1.setObjectName("pushButton_stop_1")
        self.gridLayout.addWidget(self.pushButton_stop_1, 2, 1, 1, 1)
        self.probar_1 = QtWidgets.QProgressBar(self.layoutWidget)
        self.probar_1.setProperty("value", 0)
        self.probar_1.setObjectName("probar_1")
        self.gridLayout.addWidget(self.probar_1, 2, 2, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_start_3.setText(_translate("Dialog", "Start"))
        self.pushButton_stop_3.setText(_translate("Dialog", "Stop"))
        self.pushButton_start_2.setText(_translate("Dialog", "Start"))
        self.pushButton_stop_2.setText(_translate("Dialog", "Stop"))
        self.pushButton_start_1.setText(_translate("Dialog", "Start"))
        self.pushButton_stop_1.setText(_translate("Dialog", "Stop"))
