# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'example_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(285, 293)
        self.dial = QtWidgets.QSlider(Dialog)
        self.dial.setGeometry(QtCore.QRect(27, 110, 22, 160))
        self.dial.setOrientation(QtCore.Qt.Vertical)
        self.dial.setObjectName("dial")
        self.prg = QtWidgets.QProgressBar(Dialog)
        self.prg.setGeometry(QtCore.QRect(47, 10, 201, 41))
        self.prg.setProperty("value", 0)
        self.prg.setObjectName("prg")
        self.btnStart = QtWidgets.QPushButton(Dialog)
        self.btnStart.setGeometry(QtCore.QRect(87, 60, 113, 32))
        self.btnStart.setObjectName("btnStart")
        self.lcd = QtWidgets.QLCDNumber(Dialog)
        self.lcd.setGeometry(QtCore.QRect(150, 160, 91, 91))
        self.lcd.setObjectName("lcd")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btnStart.setText(_translate("Dialog", "start"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
